# Google Cloud Build configuration
steps:
  # Install dependencies
  - name: 'node:18-alpine'
    entrypoint: 'npm'
    args: ['ci']
    
  # Build the application
  - name: 'node:18-alpine'
    entrypoint: 'npm'
    args: ['run', 'build']
    
  # Build Docker image for Cloud Run (optional)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/schemes-management:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/schemes-management:latest',
      '.'
    ]
    
  # Push to Container Registry (optional)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/schemes-management:latest']
    
  # Deploy to Cloud Storage (static hosting)
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', '-r', 'dist/*', 'gs://YOUR_BUCKET_NAME/']
    
# Artifacts to store
artifacts:
  objects:
    location: 'gs://YOUR_BUILD_ARTIFACTS_BUCKET'
    paths: ['dist/**/*']
    
# Timeout
timeout: 1200s

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'