# Cloudflare Pages configuration
[build]
command = "npm run build"
publish = "dist"
ignore = "git diff --quiet HEAD^ HEAD -- package.json package-lock.json"

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "8"

# Production environment variables
[env.production]
VITE_CLOUDFLARE_WORKER_URL = "https://schemes-management-worker.your-subdomain.workers.dev"
VITE_SUPABASE_URL = "$SUPABASE_URL"
VITE_SUPABASE_ANON_KEY = "$SUPABASE_ANON_KEY"
NODE_ENV = "production"

# Development/preview environment variables
[env.preview]
VITE_CLOUDFLARE_WORKER_URL = "https://schemes-management-worker-dev.your-subdomain.workers.dev"
VITE_SUPABASE_URL = "$SUPABASE_URL"
VITE_SUPABASE_ANON_KEY = "$SUPABASE_ANON_KEY"
NODE_ENV = "development"

# Redirects and headers
[[redirects]]
from = "/api/*"
to = "https://schemes-management-worker.your-subdomain.workers.dev/:splat"
status = 200

[[headers]]
for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"